### ISSUE TITLE
Rename of "Tech_archive" category

### ISSUE THREAD

**Issue by atamaokac** [oumpy/hp_management#113]
It should be renamed since it is not an archive any more.
Tech, Tech_blog, ...
What is good do you think?
(Due to potential technical issues, Japanese & white spaces are not recommended now, although not impossible.)

**Comment by atamaokac** [comment]
P.S. If Japanese (such as "技術ブログ") is definitely desirable, it is better to set English label temporarily and after that change it to Japanese by some effort.

**Comment by takyamamoto** [comment]
I think simply "Blog" is good.

**Comment by atamaokac** [comment]
OK.

**Comment by atamaokac** [comment]
Just a note. Japanese name is easily possible by using JINJA_FILTERS in contentconf.py, I noticed.

**Comment by atamaokac** [comment]
This is a better way. Sounds cool.
https://github.com/getpelican/pelican-plugins/tree/master/category_meta
