### ISSUE TITLE
Make video size flexible

### ISSUE THREAD

**Issue by atamaokac** [oumpy/hp_management#145]
The video size is not good for some mobile devices. It should be flexible, and it is possible by CSS tricks I think.

**Comment by atamaokac** [comment]
#147 is working, but at least on iPhone, 90vw setting is not respected and the video is still too large...

**Comment by takyamamoto** [comment]
Hmm. In my android phone, videos are shown with proper width.

**Comment by atamaokac** [comment]
#148 perfectly resolved it. Thanks!
