### ISSUE TITLE
Run failed: Deploy_on_site

### ISSUE THREAD

**Issue by takyamamoto** [oumpy/hp_management#170]
Error occurred in building of homepage with Github actions. I'm sorry but why?

**Comment by atamaokac** [comment]
It seems a problem of SSH authentication. I will look a bit more.

**Comment by atamaokac** [comment]
Original Issue: #149 
First trial PR: #162

**Comment by atamaokac** [comment]
It seems that it was a problem of SSH key format. I replaced the key. Maybe it lets the system work...

**Comment by atamaokac** [comment]
@takyamamoto Could you try it again, by merging one of my pull requests which you judge no problem.

**Comment by takyamamoto** [comment]
Thanks. But where is your PR...?

**Comment by atamaokac** [comment]
Oh... "my PRs" meant ones for articles & systems which have no relations with auto-publish. I just replaced keys registered to GitHub, and the workflow codes are untouched.

Anyway, after that, the error of key format disappeared. However still it fails in authentication for the bot GitHub account. Why???

**Comment by atamaokac** [comment]
By the way from the beginning, it succeeds to pull, initialize & compile the source, and commit it to the local repository. It fails in the final stage of pushing it to the website.

**Comment by atamaokac** [comment]
Now it is WORKING !!
