### ISSUE TITLE
Auto generator of TOC

### ISSUE THREAD

**Issue by takyamamoto** [oumpy/hp_management#42]
To read articles easier, table-of-contents (TOC) should be in the articles. However, the manually implementation of TOC takes time. It should be automatically.

`extract_toc` is one of pelican-plugins
https://github.com/getpelican/pelican-plugins/tree/master/extract_toc

But it requires BeautifulSoup.
`pip install beautifulsoup4`

**Comment by takyamamoto** [comment]
fastpagesを参考にしてheaderにこれを入れれば良いかも
https://github.com/fastai/fastpages/blob/1b3e534fa9ec766dffbd5f2737a4129028665d66/_includes/toc.html

**Comment by atamaokac** [comment]
`Pelican-toc` <https://github.com/ingwinlu/pelican-toc>
looks better than `extract_toc`.
I have no idea which of this and javascript is better.

**Comment by takyamamoto** [comment]
TOC, 自動生成できたものの若干バグがある。リンクが正常に作動していない。

**Comment by takyamamoto** [comment]
最終的に
https://ndabas.github.io/toc/
を参考にして作成。
バグも無くなった
