### ISSUE TITLE
Updating top-page agenda

### ISSUE THREAD

**Issue by atamaokac** [oumpy/hp_management#442]
@abebe9849 How about updating or rewriting the agenda on the top page? It is very old, just copied from the previous website, and may not well-fit the current status of the party and what the present executive consider to be important.

**Comment by abebe9849** [comment]
the agenda on the top page means 
"""
大阪大学医学部Python会（正式名：情報医科学研究会）とは、大阪大学医学部の学生が中心となり、プログラミング言語Pythonを軸に、医療分野と絡めて個人の研究・趣味に取り組む会です。

RNA発現データ、がんゲノムの遺伝子変異、患者の画像データなど、医療データはこれまでの常識では考えられないスピードで増加しています。 bioinformatics、脳科学、医療情報学や画像解析など様々な分野において、メンバーそれぞれが日々研鑽しています。

学部１回生から６回生まで参加しており、学年を超えて自由に活動しています。 定期的に勉強会・交流会を開き、メンバー同士の情報交換を目的に交流しております。 Python会に興味のある方はぜひ、Contactのページからご連絡ください。お待ちしております。

―Pythonで医学に貢献を―
""" in https://oumpy.github.io/ ?

**Comment by atamaokac** [comment]
Yes it is. Maybe it is more like an introduction than an agenda... please don't care.
