### ISSUE TITLE
Comment system

### ISSUE THREAD

**Issue by takyamamoto** [oumpy/hp_management#73]
I think the comment system should be implemented.

## utteranc.es
fastpages implements comment system with utteranc.es
- https://utteranc.es/
- https://qiita.com/cannorin/items/cd23018b39c2987c6de2

## 過去の案
https://github.com/getpelican/pelican-plugins/tree/666716e1f678f0d7f2ed020ad239fabb3a3c6a49/pelican_comment_system

PelicanにDisqusでコメント欄を埋め込む
※ **現在のvoidy-bootstrapにDisqusを埋め込む機能はあるが、trackingしたり広告が追加されたようで**…
https://raimon49.github.io/2014/11/20/embed-comments-in-pelican.html

Isso でブログにコメント機能を導入する
https://blog.uedder.com/comment-system-on-pelican-with-isso.html

**Comment by takyamamoto** [comment]
使用した様子です。

# 記事にコメントする
コメントにはGithubアカウントでのログインが必要です。テストで自分の記事にコメントしました。
https://oumpy.github.io/articles/2019/06/DABEST_tutorial.html

![image](https://user-images.githubusercontent.com/41336057/77892704-fc898100-72ad-11ea-8022-4a0c8b42e3d8.png)

**Comment by atamaokac** [comment]
Looks cool !

**Comment by atamaokac** [comment]
The only regrettable point is that it is github-locked and not looks strong against a large deformation of the site constitution accompanying URL changes.

Another way I just found is to use pelican_comment_system
<https://github.com/getpelican/pelican-plugins/tree/master/pelican_comment_system>.
This seems to be one to send the comment information as an e-mail, so making a server-side system to receive it & autoupdate the site would not be a too hard task...

**Comment by atamaokac** [comment]
utteranc.es is better in that it uses github certification, which prevents anonymous posts which potentially make some bad effects.

**Comment by takyamamoto** [comment]
I think so. Our blog is technical blog, so I think those who write beneficial comments may have github account.
