### ISSUE TITLE
Auto-generated "Open in Colab"

### ISSUE THREAD

**Issue by takyamamoto** [oumpy/hp_management#74]
I think to implementation of the link of "open in colab", the link should be inserted into the base.html in pelican-ipynb plugin.

https://github.com/danielfrg/pelican-ipynb/blob/f58e12480d8b888525648d876fe86c6b405cf45a/tests/pelican/theme/templates/base.html

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %} | {{ SITENAME }}</title>
    </head>
    <!- ここにlinkを挿入->
    <body>
        {% block content %}{% endblock %}
    </body>
</html>
```

**Comment by atamaokac** [comment]
I do not understand it very well yet, but it looks to me that we should put the link in the content_header appearing in the base.html of voidy-boostrap we are using.

**Comment by atamaokac** [comment]
It should be inserted to (a replacing file of) template/article_header_info.html.
I think we can also find some flag to detect that an article is converted from a jupyter notebook, in the source code of  pelican-ipynb.

**Comment by takyamamoto** [comment]
※日本語で書きます。
pull requestが連続してすみませんでした。かなり無理やりな方法になってしまったのですが、現状は満足しています。

![image](https://user-images.githubusercontent.com/41336057/77969104-efa77480-7323-11ea-92ac-75343f354049.png)

まず、元がipynbファイルの記事には`highlight hl-ipython3`というclassが含まれることに気づいたので、このclassが含まれていればColabへのリンクを生成することにしました。

custom headerとfooterを新たに作成しました。`open_in_colab_footer.html`で`highlight hl-ipython3`の有無を判別し、classがあればcolabへのリンクを生成し、`open_in_colab_header.html`で表示する、という流れです。ついでにgithubで開くためのリンクも作成しました。

ただ、この過程において、どうしてもファイルの年次と、content内の年次を合わせる必要があったので、**記事を年度別ではなく、年別に管理することにしました**。
https://github.com/oumpy/hp_management/pull/89

よろしくお願いいたします。

**Comment by atamaokac** [comment]
The produced website looks good. But in the source level, why can't it be school-year base? I do not know but I think it should be easy to solve. It can be computed from year & month, which I don't know any kind of javascript that can't execute.

Anyway it involves a large change in the article tree, and I think you should not accept such a master-branch pull request by yourself.

**Comment by takyamamoto** [comment]
I'm so sorry...
